name: publish-cli-release

on:
  workflow_dispatch:

  pull_request:
    paths:
      - .github/workflows/publish-cli-release.yml
      - .github/scripts/publish-unpublished-rpms-to-archive.sh
    branches:
      - master

  push:
    paths:
      - .github/workflows/publish-cli-release.yml
      - .github/scripts/publish-unpublished-rpms-to-archive.sh
    branches:
      - master
      - glebashnik/gh-action-publish-cli-release

  schedule:
   - cron: '0 6 * * *'

jobs:
  publish-cli-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull docker image
        run: docker pull homebrew/brew:latest

      - name: publish-github
        run: |
          docker run -rm \
            -e HOMEBREW_GITHUB_API_TOKEN=${{ secrets.HOMEBREW_GITHUB_API_TOKEN }} \
            -e GH_TOKEN=${{ secrets.GH_TOKEN }} \
            -v ${{ github.workspace }}:/workspace -w /workspace \
            docker.io/almalinux:8 bash -c "
              export HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_ANALYTICS=1
              brew install --quiet gh zip go
              make -C client/go clean dist-github
            "

      - name: publish-homebrew
        run: |
          docker run -rm \
            -e HOMEBREW_GITHUB_API_TOKEN=${{ secrets.HOMEBREW_GITHUB_API_TOKEN }} \
            -e GH_TOKEN=${{ secrets.GH_TOKEN }} \
            -v ${{ github.workspace }}:/workspace -w /workspace \
            docker.io/almalinux:8 bash -c "
              export HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_ANALYTICS=1
              brew install --quiet gh zip go
              make -C client/go clean dist-homebrew
            "

      - name: verify-brew-install
        run: |
            docker run -rm \
            -e HOMEBREW_GITHUB_API_TOKEN=${{ secrets.HOMEBREW_GITHUB_API_TOKEN }} \
            -e GH_TOKEN=${{ secrets.GH_TOKEN }} \
            -v ${{ github.workspace }}:/workspace -w /workspace \
            docker.io/almalinux:8 bash -c "
              export HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_ANALYTICS=1
              brew install --quiet gh zip go
              make -C client/go install-brew
            "

